### Code Hist.

- CODE  
  &ensp; : KIER Data_단순 분리 (전처리 X)  

- DESC  
  &emsp; [수행 작업]  
  &emsp; 1) Date 형식 검사 및 이상치 처리  
  &emsp;&emsp; 1-1) Datetime 유효성 확인  
  &emsp;&emsp; 1-2) Datetime 이상치 제거  
  &emsp; 2) 세대별 사용량 분리  
  &emsp;&emsp; 2-1) HOUSE_ID를 기반으로 적산 사용량 분리  
  &emsp;&emsp; 2-2) 세대별 적산 사용량을 .csv 파일로 저장  
  &emsp;&emsp; 2-3) 세대별 분리된 적산 사용량을 Combine  

- DATE  
  &ensp; 2023-10-12 Created  
  &ensp; 2023-11-21 Code 최신화  
  &emsp;&emsp;&emsp;&emsp;&emsp;&emsp; 1) 기존 모듈화된 함수 사용  
  &emsp;&emsp;&emsp;&emsp;&emsp;&emsp; 2) 기존 KIER 변환 관련 코드를 모두 통합  
  &ensp; 2024-01-19 Code 개선  
  &emsp;&emsp;&emsp;&emsp;&emsp;&emsp; 1) 공통코드 사용 경로 개선, Raw로 저장  
  &emsp;&emsp;&emsp;&emsp;&emsp;&emsp; 2) HOT (온수 사용량) 전용 Code 작성  
  &ensp; 2024-03-13 Code 개선  
  &emsp;&emsp;&emsp;&emsp;&emsp;&emsp; 1) 공통코드 사용 경로 개선, Raw로 저장  
  &ensp; 2024-06-27 Code 개선  
  &emsp;&emsp;&emsp;&emsp;&emsp;&emsp; 1) GAS Domain 추가

## 01. Code

### 01-01. Init

#### 01-01-01. Init_Module Import

#### Module import

In [1]:
#region Basic_Import
## Basic
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
os.path.dirname(os.path.abspath('__file__'))
import sys
sys.path.append(os.path.dirname(os.path.abspath(os.path.dirname('__file__'))))

import warnings
warnings.filterwarnings('ignore')

import numpy as np, pandas as pd
from pandas import DataFrame, Series

import math, random

## Datetime
import time
import datetime as dt
from datetime import datetime, date, timedelta

import glob
from glob import glob
import requests
import json

## 시각화
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['figure.figsize'] = [10, 8]

from scipy import stats

# K-Means 알고리즘
from sklearn.cluster import KMeans, MiniBatchKMeans

# CLustering 알고리즘의 성능 평가 측도
from sklearn.metrics import homogeneity_score, completeness_score, v_measure_score, adjusted_rand_score, silhouette_score, rand_score, calinski_harabasz_score, davies_bouldin_score
from sklearn.metrics.cluster import contingency_matrix

## 정규화
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn import metrics

import urllib
from urllib.request import urlopen
from urllib.parse import urlencode, unquote, quote_plus

from selenium import webdriver
from selenium.webdriver.chrome.service import Service

from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup

from tqdm.notebook import tqdm
import tqdm

## Init.
pd.options.display.float_format = '{:.10f}'.format
#endregion Basic_Import

In [2]:
## Import_DL
str_tar = "tf"
## For Torch
if str_tar == "torch":
    import torch
    import torch.nn as nn
    from torch.nn.utils import weight_norm
    print("Torch Imported")
## For TF
elif str_tar == "tf":
    import tensorflow as tf
    import tensorflow_addons as tfa
    from keras.callbacks import EarlyStopping, ModelCheckpoint
    from keras.models import Sequential, load_model
    from keras_flops import get_flops
    print("Tensorflow Imported")
else:
    print("Error : Cannot be used except for Keywords")
    print(" : torch / tf")

Tensorflow Imported

In [3]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

tf.debugging.set_log_device_placement(True)
gpus = tf.config.list_physical_devices('GPU')
if gpus:
  # 텐서플로가 첫 번째 GPU만 사용하도록 제한
  try:
    print('Using GPU')
    tf.config.set_visible_devices(gpus[0], 'GPU')
  except RuntimeError as e:
    # 프로그램 시작시에 접근 가능한 장치가 설정되어야만 합니다
    print(e)
else : 
  print('Using CPU')

Using GPU

In [4]:
## Import_Local
from Src_Dev_Common import DEV_Common_Data_Datetime as com_date
# from Src_Dev_Common import DEV_KASI_Holiday as com_Holi
# from Src_Dev_Common import DEV_Common_Data_Analysis as com_Analysis
# from Src_Dev_Common import DEV_Common_Data_Preprocessing as com_Prep
# from Src_Dev_Common import DEV_Common_Model as com_Model
# from Src_Dev_Common import DEV_Common_Data_Visualization as com_Visual
# from Src_Dev_Common import DEV_KMA_Weather_ASOS as com_ASOS
# from Src_Dev_Common import DEV_KDHC_Usage as com_KDHC
# from Src_Dev_Common import DEV_KIER_Usage as com_KIER

### 01-01-02. Config (Directory, Params)

In [5]:
## Init_config
SEED = 42

np.random.seed(SEED)
tf.random.set_seed(SEED)
random.seed(SEED)
os.environ["PYTHONHASHSEED"], os.environ['TF_DETERMINISTIC_OPS'] = str(SEED), "1"

In [6]:
## Define Todate str
str_now_ymd = pd.datetime.now().date()
str_now_y, str_now_m, str_now_d = pd.datetime.now().year, pd.datetime.now().month, pd.datetime.now().day
str_now_hr, str_now_min = pd.datetime.now().hour, pd.datetime.now().minute

print(pd.datetime.now())
print(str(str_now_y) + " / " + str(str_now_m)  + " / " + str(str_now_d))
print(str(str_now_hr) + " : " + str(str_now_min))

2024-07-02 19:18:59.773758
2024 / 7 / 2
19 : 18

In [7]:
## Dict_Domain
dict_domain = {0:"ELEC", 1:"HEAT", 2:"WATER", 3:"HOT_HEAT", 4:"HOT_FLOW", 5:"GAS"} ## GAS는 사용하지 않음.
int_domain = 2
str_domain = str(dict_domain[int_domain])

dict_col_accu = {0 : "ACTUAL_ACCU_EFF" ## ELEC
                 , 1 : "ACCU_HEAT" ## HEAT
                 , 2 : "ACCU_FLOW" ## WATER
                 , 3 : "ACCU_HEAT" ## HOT 열량
                 , 4 : "ACCU_FLOW" ## HOT 유량
                 , 5 : "ACCU_FLOW"} ## GAS
str_col_accu = str(str_domain + "_" + str(dict_col_accu[int_domain]))

dict_col_inst = {0 : "INST_EFF" ## ELEC_INST_EFF
                , 1 : "INST_HEAT" ## HEAT_INST_HEAT
                , 2 : "INST_FLOW" ## WATER_INST_FLOW
                , 3 : "INST" ## HOT_HEAT_INST
                , 4 : "INST" ## HOT_FLOW_INST
                , 5 : "INST_FLOW"} ## GAS_INST_FLOW
str_col_inst = str(str_domain + "_" + str(dict_col_inst[int_domain]))

## Directory Root
str_dirData = "../data/data_Energy_KIER/"
str_dir_raw = '../data/data_Energy_KIER/KIER_0_Raw/'
str_dirName_bld = '../data/data_Energy_KIER/KIER_1_BLD/'
str_dirName_h = '../data/data_Energy_KIER/KIER_2_H_' + str_domain + '/'

## File
str_fileRaw = str('KIER_RAW_' + str_domain + '_2024-06-07.csv')
str_fileRaw_hList = str('KIER_hList_Common.csv') 

print(str(os.listdir(str_dirData)) + "\n")
print(os.listdir(str_dirName_h))

['.ipynb_checkpoints', 'BS_CONFIGURATION_202309251452.csv', 'DATE_1M_2023-10-20.csv', 'KIER 전처리 현황_2024-06-25.xlsx', 'KIER_0_Raw', 'KIER_1_BLD', 'KIER_2_H_ELEC', 'KIER_2_H_GAS', 'KIER_2_H_HEAT', 'KIER_2_H_HOT_FLOW', 'KIER_2_H_HOT_HEAT', 'KIER_2_H_WATER', 'KIER_ASOS_WEATHER_DAILY_202309251521.csv', 'KIER_ASOS_WEATHER_HOUR_202309251521.csv', 'KIER_DATA_OLD', 'KIER_ETC', 'KIER_hList_Comparison_2024-06-26.xlsx', 'KIER_List_Table_Column_2023-09-25.xlsx', 'KIER_Query_2023-09-25.txt', 'KMA_ASOS_119_2010_2023_1st_to CSV.csv', '[IITP] 데이터 테이블 정리 (공유 원본).docx']


In [8]:
## "KIER_01-01_Data_hList.ipynb"로부터 만들어진 Bld/F/H List
df_kier_hList = pd.read_csv(str_dir_raw + str_fileRaw_hList, index_col = 0)
list_Bld = df_kier_hList['HOUSE_ID_DONG'].drop_duplicates()
print(df_kier_hList.columns)
df_kier_hList

Index(['HOUSE_ID_DONG', 'HOUSE_ID_HO_PRE', 'HOUSE_ID_HO_INT', 'HOUSE_ID',
       'HOUSE_ID_HO'],
      dtype='object')

,HOUSE_ID_DONG,HOUSE_ID_HO_PRE,HOUSE_ID_HO_INT,HOUSE_ID,HOUSE_ID_HO
1,561,1,1,561-1-1,NkI4M0EzNDYxQTE1MDJERjM4NURERTcyRjdGQTJDMDU=
2,561,1,2,561-1-2,ODBEOTE0QzZCMjg5RUMzNTRBQjM1NjE0RDNBNDE0NzU=
3,561,1,3,561-1-3,QTUwRUJDQTlBMkZENUQyNjg0RDRGREVFMTNGNDI3NUY=
4,561,1,4,561-1-4,RkRCQzY4OTlCMTRDQjgzNUZBREE3Njc2MkM2MUM2QjI=
5,561,2,1,561-2-1,MTQxNkQ1RDAzOTE5NTM5RUM3MzlDQkY3RTI2NERCQTM=
...,...,...,...,...,...
344,563,23,2,563-23-2,QkJCQjQwOThFNjgwNjUwQzJGRUJFNDlCNTREOEUxNDU=
345,563,23,3,563-23-3,QUJENzFFMEFDRjM4MjY3NTRDQzJCRjdDNUQ3ODA0N0Y=
346,563,23,4,563-23-4,RUVENzZDNTc4MUY4NDg5MUREQjZEOUM1M0Q2RjYzMDE=
347,563,24,1,563-24-1,NEVENDc1OTFFNDBBRjBDQzkzMTlEMDgzMkMzMkZFQTg=
348,563,24,2,563-24-2,ODgwNDU1RUU0RUQ2OTQxQTBGMEI3MTE3NTkxODYxQ0U=

In [9]:
str_file = 'KIER_' + str_domain + '_ACCU_10MIN.csv'       
df_kier_extract = pd.read_csv(str_dirName_h + str_file)
df_kier_extract.isna().sum()

Unnamed: 0                        0
YEAR                              0
MONTH                             0
DAY                               0
HOUR                              0
                             ...
WATER_ACCU_FLOW_563-23-4    2664992
WATER_ACCU_FLOW_563-24-1    2665185
WATER_ACCU_FLOW_563-24-2    2665057
MEAN_OF_ACCU                2663716
SUM_OF_ACCU                       0
Length: 356, dtype: int64

## 01-02. Data Load (df_raw)

### 01-02-01. KIER (Energy Usage)

In [10]:
## "METER_DATE" Cleansing이 완료되지 않은 경우
## Gas의 경우는 ParserError: Error tokenizing data 발생하므로 아래와 같이 Load
df_raw = pd.read_csv(str_dir_raw + str_fileRaw, index_col= 0, error_bad_lines = False).reset_index()
## 단, warn_bad_lines는 True로 그대로 두어 어느 행이 사라졌는지 확인해야만 함

print(df_raw.shape, " /// ", df_raw.columns)
df_raw

(32868970, 5)  ///  Index(['METER_DATE', 'HOUSE_ID_DONG', 'HOUSE_ID_HO_PRE', 'HOUSE_ID_HO',
       'WATER_ACCU_FLOW'],
      dtype='object')

,METER_DATE,HOUSE_ID_DONG,HOUSE_ID_HO_PRE,HOUSE_ID_HO,WATER_ACCU_FLOW
0,2022-07-17 23:20:00,561,1,NkI4M0EzNDYxQTE1MDJERjM4NURERTcyRjdGQTJDMDU=,51.8681000000
1,2022-07-17 23:30:00,561,1,NkI4M0EzNDYxQTE1MDJERjM4NURERTcyRjdGQTJDMDU=,51.8681000000
2,2022-07-17 23:40:00,561,1,NkI4M0EzNDYxQTE1MDJERjM4NURERTcyRjdGQTJDMDU=,51.8681000000
3,2022-07-17 23:50:00,561,1,NkI4M0EzNDYxQTE1MDJERjM4NURERTcyRjdGQTJDMDU=,51.9031000000
4,2022-07-18 00:00:00,561,1,NkI4M0EzNDYxQTE1MDJERjM4NURERTcyRjdGQTJDMDU=,51.9034000000
...,...,...,...,...,...
32868965,2024-06-05 13:40:30,563,24,ODgwNDU1RUU0RUQ2OTQxQTBGMEI3MTE3NTkxODYxQ0U=,332.6307000000
32868966,2024-06-05 14:00:30,563,24,ODgwNDU1RUU0RUQ2OTQxQTBGMEI3MTE3NTkxODYxQ0U=,332.6308000000
32868967,2024-06-05 14:10:30,563,24,ODgwNDU1RUU0RUQ2OTQxQTBGMEI3MTE3NTkxODYxQ0U=,332.6308000000
32868968,2024-06-05 14:30:29,563,24,ODgwNDU1RUU0RUQ2OTQxQTBGMEI3MTE3NTkxODYxQ0U=,332.6308000000
32868969,2024-06-05 14:40:29,563,24,ODgwNDU1RUU0RUQ2OTQxQTBGMEI3MTE3NTkxODYxQ0U=,332.6308000000

In [11]:
## 1) Date Column에 대한 유효성 검사 및 이상 Data에 대한 소거
## 1-1) Datetime 유효성 확인
list_errValues = com_date.list_invalidDate(df_raw, 'METER_DATE')
print(len(list_errValues))
## 1-2) Datetime 이상치 제거
for i in range(len(list_errValues) - 1, -1, -1):
    df_raw = df_raw.drop(index = list_errValues[i], axis = 0)

print(df_raw.shape)

(32868970, 5)
12
[15223800, 15223801, 15223802, 15223803, 15223804, 19964817, 19964818, 19964819, 26462333, 26462334, 26462335, 26462336]
12
(32868958, 5)

In [12]:
## List의 'HOUSE_ID_HO_INT' Column을 df_raw에 Merge
df_raw = df_raw[['METER_DATE', 'HOUSE_ID_DONG', 'HOUSE_ID_HO_PRE', 'HOUSE_ID_HO'
                , str_col_accu]]

df_raw = pd.merge(df_raw, df_kier_hList
                  , how = 'left', on = ['HOUSE_ID_DONG', 'HOUSE_ID_HO_PRE', 'HOUSE_ID_HO'])
df_raw = df_raw[['METER_DATE', 'HOUSE_ID', 'HOUSE_ID_DONG', 'HOUSE_ID_HO_PRE', 'HOUSE_ID_HO_INT', 'HOUSE_ID_HO'
                , str_col_accu]]

str_fileCleansed = str('KIER_RAW_' + str_domain + '_Cleansed.csv')
df_raw.to_csv(str_dir_raw + str_fileCleansed)
df_raw

,METER_DATE,HOUSE_ID,HOUSE_ID_DONG,HOUSE_ID_HO_PRE,HOUSE_ID_HO_INT,HOUSE_ID_HO,WATER_ACCU_FLOW
0,2022-07-17 23:20:00,561-1-1,561,1,1,NkI4M0EzNDYxQTE1MDJERjM4NURERTcyRjdGQTJDMDU=,51.8681000000
1,2022-07-17 23:30:00,561-1-1,561,1,1,NkI4M0EzNDYxQTE1MDJERjM4NURERTcyRjdGQTJDMDU=,51.8681000000
2,2022-07-17 23:40:00,561-1-1,561,1,1,NkI4M0EzNDYxQTE1MDJERjM4NURERTcyRjdGQTJDMDU=,51.8681000000
3,2022-07-17 23:50:00,561-1-1,561,1,1,NkI4M0EzNDYxQTE1MDJERjM4NURERTcyRjdGQTJDMDU=,51.9031000000
4,2022-07-18 00:00:00,561-1-1,561,1,1,NkI4M0EzNDYxQTE1MDJERjM4NURERTcyRjdGQTJDMDU=,51.9034000000
...,...,...,...,...,...,...,...
32868953,2024-06-05 13:40:30,563-24-2,563,24,2,ODgwNDU1RUU0RUQ2OTQxQTBGMEI3MTE3NTkxODYxQ0U=,332.6307000000
32868954,2024-06-05 14:00:30,563-24-2,563,24,2,ODgwNDU1RUU0RUQ2OTQxQTBGMEI3MTE3NTkxODYxQ0U=,332.6308000000
32868955,2024-06-05 14:10:30,563-24-2,563,24,2,ODgwNDU1RUU0RUQ2OTQxQTBGMEI3MTE3NTkxODYxQ0U=,332.6308000000
32868956,2024-06-05 14:30:29,563-24-2,563,24,2,ODgwNDU1RUU0RUQ2OTQxQTBGMEI3MTE3NTkxODYxQ0U=,332.6308000000
32868957,2024-06-05 14:40:29,563-24-2,563,24,2,ODgwNDU1RUU0RUQ2OTQxQTBGMEI3MTE3NTkxODYxQ0U=,332.6308000000

In [13]:
## "METER_DATE" Cleansing이 완료된 경우
str_fileCleansed = str('KIER_RAW_' + str_domain + '_Cleansed.csv')
df_raw = pd.read_csv(str_dir_raw + str_fileCleansed, index_col = 0)
print(df_raw.shape, " /// ", df_raw.columns)
df_raw

(32868958, 7)  ///  Index(['METER_DATE', 'HOUSE_ID', 'HOUSE_ID_DONG', 'HOUSE_ID_HO_PRE',
       'HOUSE_ID_HO_INT', 'HOUSE_ID_HO', 'WATER_ACCU_FLOW'],
      dtype='object')

,METER_DATE,HOUSE_ID,HOUSE_ID_DONG,HOUSE_ID_HO_PRE,HOUSE_ID_HO_INT,HOUSE_ID_HO,WATER_ACCU_FLOW
0,2022-07-17 23:20:00,561-1-1,561,1,1,NkI4M0EzNDYxQTE1MDJERjM4NURERTcyRjdGQTJDMDU=,51.8681000000
1,2022-07-17 23:30:00,561-1-1,561,1,1,NkI4M0EzNDYxQTE1MDJERjM4NURERTcyRjdGQTJDMDU=,51.8681000000
2,2022-07-17 23:40:00,561-1-1,561,1,1,NkI4M0EzNDYxQTE1MDJERjM4NURERTcyRjdGQTJDMDU=,51.8681000000
3,2022-07-17 23:50:00,561-1-1,561,1,1,NkI4M0EzNDYxQTE1MDJERjM4NURERTcyRjdGQTJDMDU=,51.9031000000
4,2022-07-18 00:00:00,561-1-1,561,1,1,NkI4M0EzNDYxQTE1MDJERjM4NURERTcyRjdGQTJDMDU=,51.9034000000
...,...,...,...,...,...,...,...
32868953,2024-06-05 13:40:30,563-24-2,563,24,2,ODgwNDU1RUU0RUQ2OTQxQTBGMEI3MTE3NTkxODYxQ0U=,332.6307000000
32868954,2024-06-05 14:00:30,563-24-2,563,24,2,ODgwNDU1RUU0RUQ2OTQxQTBGMEI3MTE3NTkxODYxQ0U=,332.6308000000
32868955,2024-06-05 14:10:30,563-24-2,563,24,2,ODgwNDU1RUU0RUQ2OTQxQTBGMEI3MTE3NTkxODYxQ0U=,332.6308000000
32868956,2024-06-05 14:30:29,563-24-2,563,24,2,ODgwNDU1RUU0RUQ2OTQxQTBGMEI3MTE3NTkxODYxQ0U=,332.6308000000
32868957,2024-06-05 14:40:29,563-24-2,563,24,2,ODgwNDU1RUU0RUQ2OTQxQTBGMEI3MTE3NTkxODYxQ0U=,332.6308000000

In [14]:
## 각 세대별 적산값을 파일로 저장
list_h_id = df_kier_hList['HOUSE_ID'].drop_duplicates()

## ▶ Sub-Task 01 : 최적의 Period 계산을 위한, 세대별 Time Period 추출
dt_start, dt_end = 0, 0 ## 최종 시점 및 종점
df_kier_h_Combined = pd.DataFrame() ## 각 호별 Resampled Data 생성 및 취합을 위한 DataFrame
## Sub-Task 01 ◀

for h_id in list_h_id:
    print(h_id)
    df_h_tmp = df_raw[(df_raw['HOUSE_ID'] == h_id)]

    str_col_accu_h = str_col_accu + "_" + h_id

    df_h_tmp['HOUSE_ID_DONG'] = df_h_tmp['HOUSE_ID_DONG'].astype('int').astype('string')
    df_h_tmp['HOUSE_ID_HO_PRE'] = df_h_tmp['HOUSE_ID_HO_PRE'].astype('int').astype('string')
    df_h_tmp['HOUSE_ID_HO'] = df_h_tmp['HOUSE_ID_HO'].astype('string')
    df_h_tmp['HOUSE_ID'] = df_h_tmp['HOUSE_ID'].astype('string')

    df_h_tmp['METER_DATE'] = pd.to_datetime(df_h_tmp['METER_DATE'])
    df_h_tmp = com_date.create_col_ymdhm(df_h_tmp, 'METER_DATE')

    ## METER_DATE의 Minute이 10분 단위가 아닌 경우, 10분 단위로 변경
    for i in range(0, len(df_h_tmp)):
        df_h_tmp['MINUTE'].iloc[i] = (math.floor(df_h_tmp['MINUTE'].iloc[i]/10))*10
    
    int_len_start = len(df_h_tmp)

    ## 변경된 시간값을 기반으로 "METER_DATE" Column을 다시 생성
    ## "METER_DATE"가 중복된 Row를 제거
    ## 1) YMDHM 중, 중복이 있으면 그 중복을 기반으로 Merge 시 유효하지 않은 값들이 발생, Data Row 수가 몇백만 건으로 불어난다.
    ## 2) 적산 Nan값을 제거 : 세대 정보의 Nan값을 복원한 후 dropna()
    df_h_tmp = com_date.create_col_datetime(df_h_tmp, 'METER_DATE', 'YEAR', 'MONTH', 'DAY', 'HOUR', 'MINUTE').drop_duplicates(subset = 'METER_DATE').dropna()

    ## ▶ Sub-Task 01. 각 세대별 Time Period 연산
    if dt_start == 0: 
        dt_start = df_h_tmp['METER_DATE'].min()
        print(dt_start)
    else : 
        if dt_start < df_h_tmp['METER_DATE'].min(): 
            dt_start = df_h_tmp['METER_DATE'].min()
            print("True Start")
    
    if dt_end == 0: 
        dt_end = df_h_tmp['METER_DATE'].max()
        print(dt_end)
    else : 
        if dt_start > df_h_tmp['METER_DATE'].max(): 
            dt_start = df_h_tmp['METER_DATE'].max()
            print("True End")
    ## Sub-Task 01 종료 ◀

    df_h_tmp = df_h_tmp[['YEAR', 'MONTH', 'DAY', 'HOUR', 'MINUTE', str_col_accu]]
    df_h_tmp = df_h_tmp.rename(columns = {str_col_accu : str_col_accu_h})

    int_len_end = len(df_h_tmp)
    if int_len_start != int_len_end: print(int_len_start, ' / ', int_len_end)

    str_df_h = str('KIER_' + str_domain + '_' + h_id + '_ACCU_01_Raw.csv')
    df_h_tmp.to_csv(str_dirName_h + str_df_h)

print(dt_start, " ~ ", dt_end)
print(df_h_tmp.shape, " /// ", df_h_tmp.columns)
print(df_h_tmp)

561-1-1
2022-07-17 23:20:00
2024-06-05 15:20:00
94204  /  94151
561-1-2
94197  /  94142
561-1-3
94188  /  94133
561-1-4
93844  /  93784
561-2-1
94194  /  94143
561-2-2
94046  /  93988
561-2-3
94193  /  94138
561-2-4
94211  /  94156
561-3-1
94119  /  94063
561-3-2
94207  /  94153
561-3-3
94194  /  94139
561-3-4
94178  /  94125
561-4-1
94137  /  94081
561-4-2
94195  /  94140
561-4-3
94236  /  94185
561-4-4
94166  /  94113
561-5-1
94222  /  94165
561-5-2
94122  /  94066
561-5-3
94170  /  94116
561-5-4
94171  /  94118
561-6-1
94152  /  94096
561-6-2
94197  /  94143
561-6-3
94247  /  94193
561-6-4
94175  /  94122
561-7-1
94255  /  94201
561-7-2
94167  /  94113
561-7-3
94159  /  94103
561-7-4
94180  /  94125
561-8-1
94111  /  94059
561-8-2
94195  /  94140
561-8-3
94159  /  94107
561-8-4
94258  /  94204
561-9-1
94177  /  94116
561-9-2
94119  /  94063
561-9-3
94263  /  94208
561-9-4
94168  /  94110
561-10-1
94174  /  94123
561-10-2
94131  /  94077
561-10-3
94211  /  94158
561-10-4
94237  /  94183
561-11-1
92443  /  92391
561-11-2
94139  /  94084
561-11-3
94212  /  94158
561-11-4
94161  /  94109
561-12-1
94197  /  94144
561-12-2
94140  /  94087
561-12-3
94264  /  94210
561-12-4
94173  /  94120
561-13-1
94142  /  94089
561-13-2
94265  /  94211
561-13-3
94203  /  94149
561-13-4
94172  /  94121
561-14-1
94201  /  94144
561-14-2
94156  /  94100
561-14-3
94281  /  94227
561-14-4
94184  /  94131
561-15-1
94165  /  94109
561-15-2
94278  /  94224
561-15-3
94205  /  94149
561-15-4
94180  /  94129
561-16-1
94206  /  94151
561-16-2
94174  /  94123
561-16-3
94281  /  94229
561-16-4
94180  /  94127
561-17-1
94203  /  94152
561-17-2
94181  /  94128
561-17-3
94179  /  94128
561-17-4
94309  /  94257
561-18-1
94210  /  94159
561-18-2
94302  /  94245
561-18-3
94179  /  94124
561-18-4
94190  /  94138
562-1-1
95182  /  95137
562-1-2
95096  /  95051
562-1-3
95194  /  95148
562-1-4
95079  /  95034
562-1-5
93423  /  93364
562-1-6
95079  /  95029
562-2-1
95083  /  95037
562-2-2
95199  /  95153
562-2-3
95087  /  95039
562-2-4
95097  /  95052
562-2-5
93716  /  93655
562-2-6
95189  /  95144
562-3-1
95089  /  95041
562-3-2
93831  /  93771
562-3-3
95215  /  95168
562-3-4
95196  /  95149
562-3-5
95091  /  95045
562-3-6
95093  /  95047
562-4-1
95194  /  95147
562-4-2
93883  /  93823
562-4-3
95095  /  95048
562-4-4
95097  /  95052
562-4-5
94799  /  94753
562-4-6
95095  /  95050
562-5-1
93156  /  93096
562-5-2
95214  /  95168
562-5-3
95094  /  95048
562-5-4
95097  /  95051
562-5-5
95094  /  95048
562-5-6
95189  /  95144
562-6-1
95099  /  95052
562-6-2
95201  /  95155
562-6-3
93928  /  93868
562-6-4
95087  /  95042
562-6-5
95218  /  95172
562-6-6
95098  /  95052
562-7-1
95215  /  95170
562-7-2
93937  /  93876
562-7-3
95093  /  95049
562-7-4
95208  /  95163
562-7-5
94864  /  94817
562-7-6
95105  /  95060
562-8-1
95090  /  95044
562-8-2
95199  /  95154
562-8-3
95119  /  95074
562-8-4
95091  /  95047
562-8-5
93962  /  93899
562-8-6
95216  /  95170
562-9-1
95193  /  95147
562-9-2
95127  /  95082
562-9-3
95096  /  95050
562-9-4
95219  /  95174
562-9-5
93980  /  93920
562-9-6
95100  /  95055
562-10-1
95091  /  95046
562-10-2
95075  /  95030
562-10-3
95123  /  95077
562-10-4
95213  /  95167
562-10-5
93964  /  93905
562-10-6
95210  /  95165
562-11-1
93983  /  93920
562-11-2
95219  /  95173
562-11-3
95100  /  95055
562-11-4
92093  /  92045
562-11-5
95123  /  95078
562-11-6
95088  /  95044
562-12-1
95141  /  95095
562-12-2
95195  /  95150
562-12-3
95094  /  95048
562-12-4
93984  /  93923
562-12-5
95202  /  95157
562-12-6
95086  /  95042
562-13-1
93976  /  93918
562-13-2
95191  /  95145
562-13-3
95086  /  95040
562-13-4
95211  /  95164
562-13-5
95122  /  95075
562-13-6
95090  /  95046
562-14-1
95195  /  95149
562-14-2
95140  /  95094
562-14-3
94007  /  93949
562-14-4
95095  /  95051
562-14-5
95197  /  95151
562-14-6
95091  /  95046
562-15-1
94010  /  93951
562-15-2
95097  /  95053
562-15-3
95218  /  95172
562-15-4
95139  /  95094
562-15-5
94876  /  94831
562-15-6
95110  /  95065
562-16-1
95133  /  95082
562-16-2
95077  /  95026
562-16-3
94013  /  93955
562-16-4
95214  /  95163
562-16-5
95184  /  95139
562-16-6
95087  /  95044
562-17-1
95203  /  95158
562-17-2
95142  /  95096
562-17-3
89699  /  89655
562-17-4
94026  /  93968
562-17-5
95077  /  95029
562-17-6
95212  /  95167
562-18-1
95151  /  95105
562-18-2
95199  /  95153
562-18-3
95061  /  95014
562-18-4
95217  /  95171
562-18-5
95092  /  95046
562-18-6
94045  /  93985
562-19-1
95143  /  95097
562-19-2
95200  /  95154
562-19-3
94038  /  93978
562-19-4
95203  /  95156
562-19-5
95094  /  95049
562-19-6
95084  /  95038
562-20-1
95093  /  95047
562-20-2
95196  /  95148
562-20-3
94054  /  93993
562-20-4
95210  /  95165
562-20-5
95095  /  95049
562-20-6
95173  /  95128
562-21-1
95078  /  95032
562-21-2
95161  /  95116
562-21-3
95088  /  95042
562-21-4
95207  /  95161
562-21-5
95210  /  95156
562-21-6
94037  /  93974
562-22-1
95207  /  95158
562-22-2
95096  /  95051
562-22-3
95166  /  95121
562-22-4
95094  /  95049
562-22-5
94033  /  93974
562-22-6
95198  /  95154
562-23-1
95220  /  95170
562-23-2
94030  /  93971
562-23-3
95201  /  95150
562-23-4
95176  /  95131
562-24-1
94051  /  93991
562-24-2
95198  /  95149
563-1-1
94036  /  93975
563-1-2
94182  /  94124
563-1-3
94285  /  94230
563-1-4
94070  /  94011
563-1-5
94337  /  94282
563-1-6
94041  /  93983
563-2-1
94059  /  94001
563-2-2
94287  /  94234
563-2-3
94039  /  93982
563-2-4
94192  /  94134
563-2-5
94315  /  94264
563-2-6
94254  /  94194
563-3-1
93218  /  93160
563-3-2
94338  /  94287
563-3-3
94325  /  94271
563-3-4
94235  /  94174
563-3-5
94182  /  94122
563-3-6
94062  /  93999
563-4-1
94328  /  94273
563-4-2
94349  /  94297
563-4-3
94042  /  93984
563-4-4
94185  /  94125
563-4-5
94246  /  94186
563-4-6
94079  /  94021
563-5-1
94338  /  94284
563-5-2
94245  /  94184
563-5-3
94038  /  93980
563-5-4
94192  /  94132
563-5-5
94084  /  94025
563-5-6
94310  /  94256
563-6-1
93294  /  93236
563-6-2
94313  /  94261
563-6-3
94335  /  94280
563-6-4
94213  /  94155
563-6-5
94260  /  94197
563-6-6
94088  /  94029
563-7-1
94245  /  94186
563-7-2
94328  /  94272
563-7-3
94093  /  94031
563-7-4
94330  /  94277
563-7-5
94047  /  93985
563-7-6
94211  /  94149
563-8-1
94047  /  93989
563-8-2
93912  /  93859
563-8-3
94208  /  94148
563-8-4
94074  /  94014
563-8-5
94334  /  94281
563-8-6
94244  /  94185
563-9-1
94318  /  94263
563-9-2
94223  /  94164
563-9-3
94042  /  93984
563-9-4
94259  /  94200
563-9-5
94317  /  94263
563-9-6
94101  /  94043
563-10-1
94105  /  94047
563-10-2
94062  /  94003
563-10-3
94232  /  94174
563-10-4
93822  /  93763
563-10-5
94328  /  94273
563-10-6
94321  /  94267
563-11-1
94332  /  94278
563-11-2
94253  /  94194
563-11-3
94063  /  94005
563-11-4
94322  /  94269
563-11-5
94231  /  94172
563-11-6
94104  /  94046
563-12-1
94238  /  94180
563-12-2
94326  /  94274
563-12-3
94062  /  94001
563-12-4
94019  /  93965
563-12-5
94241  /  94181
563-12-6
94099  /  94040
563-13-1
94331  /  94276
563-13-2
94344  /  94289
563-13-3
94066  /  94007
563-13-4
94248  /  94186
563-13-5
94248  /  94189
563-13-6
94102  /  94044
563-14-1
94337  /  94286
563-14-2
94241  /  94182
563-14-3
94339  /  94282
563-14-4
94048  /  93988
563-14-5
94255  /  94196
563-14-6
94092  /  94033
563-15-1
94349  /  94291
563-15-2
94043  /  93984
563-15-3
94251  /  94189
563-15-4
94235  /  94175
563-15-5
94331  /  94277
563-15-6
94101  /  94043
563-16-1
94240  /  94182
563-16-2
94115  /  94055
563-16-3
94347  /  94291
563-16-4
94261  /  94199
563-16-5
94331  /  94277
563-16-6
94053  /  93992
563-17-1
94332  /  94280
563-17-2
94243  /  94184
563-17-3
94064  /  94004
563-17-4
94316  /  94262
563-17-5
94122  /  94064
563-17-6
94259  /  94197
563-18-1
94241  /  94181
563-18-2
94252  /  94190
563-18-3
94036  /  93978
563-18-4
94334  /  94281
563-18-5
94114  /  94054
563-18-6
94353  /  94296
563-19-1
94244  /  94183
563-19-2
94255  /  94194
563-19-3
94340  /  94280
563-19-4
94317  /  94264
563-19-5
94052  /  93995
563-19-6
94123  /  94062
563-20-1
94137  /  94078
563-20-2
94325  /  94275
563-20-3
94333  /  94273
563-20-4
94266  /  94201
563-20-5
94055  /  93996
563-20-6
94241  /  94181
563-21-1
94153  /  94094
563-21-2
94247  /  94188
563-21-3
94046  /  93989
563-21-4
94248  /  94183
563-21-5
94319  /  94265
563-21-6
94336  /  94275
563-22-1
94330  /  94276
563-22-2
94056  /  93997
563-22-3
94254  /  94195
563-22-4
94134  /  94076
563-22-5
94314  /  94256
563-22-6
94263  /  94197
563-23-1
94049  /  93986
563-23-2
94164  /  94101
563-23-3
94258  /  94192
563-23-4
94240  /  94181
563-24-1
94046  /  93988
563-24-2
94174  /  94116
2022-07-17 23:20:00  ~  2024-06-05 15:20:00
(94116, 6)  ///  Index(['YEAR', 'MONTH', 'DAY', 'HOUR', 'MINUTE', 'WATER_ACCU_FLOW_563-24-2'], dtype='object')
          YEAR  MONTH  DAY  HOUR  MINUTE  WATER_ACCU_FLOW_563-24-2
32774784  2022      7   17    23      10             27.5292000000
32774785  2022      7   17    23      20             27.5292000000
32774786  2022      7   17    23      30             27.5292000000
32774787  2022      7   17    23      40             27.5293000000
32774788  2022      7   17    23      50             27.5293000000
...        ...    ...  ...   ...     ...                       ...
32868953  2024      6    5    13      40            332.6307000000
32868954  2024      6    5    14       0            332.6308000000
32868955  2024      6    5    14      10            332.6308000000
32868956  2024      6    5    14      30            332.6308000000
32868957  2024      6    5    14      40            332.6308000000

[94116 rows x 6 columns]

### 적산 사용량

#### 모든 호실의 사용량을 변수화하여 한 데이터셋에 Combine

In [15]:
## 여기서부터 실행하려 할 경우, Period를 지정해줘야함
## 정상적인 Time Period 외의 데이터는 삭제 (2022-07-17 ~ 2024-06-05)
df_period_tmp = pd.read_csv(str_dir_raw + "KIER_TIME_PERIOD.csv", index_col = 0)
df_period_tmp['METER_DATE'] = pd.to_datetime(df_period_tmp['METER_DATE'])

## 선행 계산된 Period(최종 시점 및 종점)에 대한 Date Dataframe 생성
df_kier_h_Combined = com_date.create_df_dt(pd.DataFrame(), 'METER_DATE'
                                           , df_period_tmp['METER_DATE'].min(), df_period_tmp['METER_DATE'].max(), '10min')[['YEAR', 'MONTH', 'DAY', 'HOUR', 'MINUTE']]

## METER_DATE의 Minute이 10분 단위가 아닌 경우, 10분 단위로 변경
for i in range(0, len(df_kier_h_Combined)) : df_kier_h_Combined['MINUTE'].iloc[i] = (math.floor(df_kier_h_Combined['MINUTE'].iloc[i]/10))*10
df_kier_h_Combined

       YEAR  MONTH  DAY  HOUR  MINUTE
0      2022      7   17    23       0
1      2022      7   17    23      10
2      2022      7   17    23      20
3      2022      7   17    23      30
4      2022      7   17    23      40
...     ...    ...  ...   ...     ...
99166  2024      6    5    14      40
99167  2024      6    5    14      50
99168  2024      6    5    15       0
99169  2024      6    5    15      10
99170  2024      6    5    15      20

[99171 rows x 5 columns]

In [16]:
for h_id in list_h_id:
    print(h_id)
    str_df_h = str('KIER_' + str_domain + '_' + h_id + '_ACCU_01_Raw.csv')
    df_h_tmp = pd.read_csv(str_dirName_h + str_df_h, index_col = 0).reset_index()
    # df_h_tmp['METER_DATE'] = pd.to_datetime(df_h_tmp['METER_DATE'])

    str_col_accu_h = str_col_accu + "_" + h_id
    df_h_tmp = df_h_tmp[['YEAR', 'MONTH', 'DAY', 'HOUR', 'MINUTE', str_col_accu_h]]

    df_kier_h_Combined = pd.merge(df_kier_h_Combined, df_h_tmp
                                    , how = 'left', on = ['YEAR', 'MONTH', 'DAY', 'HOUR', 'MINUTE'])
    print(df_kier_h_Combined.shape)
df_kier_h_Combined

561-1-1
(99171, 6)
561-1-2
(99171, 7)
561-1-3
(99171, 8)
561-1-4
(99171, 9)
561-2-1
(99171, 10)
561-2-2
(99171, 11)
561-2-3
(99171, 12)
561-2-4
(99171, 13)
561-3-1
(99171, 14)
561-3-2
(99171, 15)
561-3-3
(99171, 16)
561-3-4
(99171, 17)
561-4-1
(99171, 18)
561-4-2
(99171, 19)
561-4-3
(99171, 20)
561-4-4
(99171, 21)
561-5-1
(99171, 22)
561-5-2
(99171, 23)
561-5-3
(99171, 24)
561-5-4
(99171, 25)
561-6-1
(99171, 26)
561-6-2
(99171, 27)
561-6-3
(99171, 28)
561-6-4
(99171, 29)
561-7-1
(99171, 30)
561-7-2
(99171, 31)
561-7-3
(99171, 32)
561-7-4
(99171, 33)
561-8-1
(99171, 34)
561-8-2
(99171, 35)
561-8-3
(99171, 36)
561-8-4
(99171, 37)
561-9-1
(99171, 38)
561-9-2
(99171, 39)
561-9-3
(99171, 40)
561-9-4
(99171, 41)
561-10-1
(99171, 42)
561-10-2
(99171, 43)
561-10-3
(99171, 44)
561-10-4
(99171, 45)
561-11-1
(99171, 46)
561-11-2
(99171, 47)
561-11-3
(99171, 48)
561-11-4
(99171, 49)
561-12-1
(99171, 50)
561-12-2
(99171, 51)
561-12-3
(99171, 52)
561-12-4
(99171, 53)
561-13-1
(99171, 54)
561-13-2
(99171, 55)
561-13-3
(99171, 56)
561-13-4
(99171, 57)
561-14-1
(99171, 58)
561-14-2
(99171, 59)
561-14-3
(99171, 60)
561-14-4
(99171, 61)
561-15-1
(99171, 62)
561-15-2
(99171, 63)
561-15-3
(99171, 64)
561-15-4
(99171, 65)
561-16-1
(99171, 66)
561-16-2
(99171, 67)
561-16-3
(99171, 68)
561-16-4
(99171, 69)
561-17-1
(99171, 70)
561-17-2
(99171, 71)
561-17-3
(99171, 72)
561-17-4
(99171, 73)
561-18-1
(99171, 74)
561-18-2
(99171, 75)
561-18-3
(99171, 76)
561-18-4
(99171, 77)
562-1-1
(99171, 78)
562-1-2
(99171, 79)
562-1-3
(99171, 80)
562-1-4
(99171, 81)
562-1-5
(99171, 82)
562-1-6
(99171, 83)
562-2-1
(99171, 84)
562-2-2
(99171, 85)
562-2-3
(99171, 86)
562-2-4
(99171, 87)
562-2-5
(99171, 88)
562-2-6
(99171, 89)
562-3-1
(99171, 90)
562-3-2
(99171, 91)
562-3-3
(99171, 92)
562-3-4
(99171, 93)
562-3-5
(99171, 94)
562-3-6
(99171, 95)
562-4-1
(99171, 96)
562-4-2
(99171, 97)
562-4-3
(99171, 98)
562-4-4
(99171, 99)
562-4-5
(99171, 100)
562-4-6
(99171, 101)
562-5-1
(99171, 102)
562-5-2
(99171, 103)
562-5-3
(99171, 104)
562-5-4
(99171, 105)
562-5-5
(99171, 106)
562-5-6
(99171, 107)
562-6-1
(99171, 108)
562-6-2
(99171, 109)
562-6-3
(99171, 110)
562-6-4
(99171, 111)
562-6-5
(99171, 112)
562-6-6
(99171, 113)
562-7-1
(99171, 114)
562-7-2
(99171, 115)
562-7-3
(99171, 116)
562-7-4
(99171, 117)
562-7-5
(99171, 118)
562-7-6
(99171, 119)
562-8-1
(99171, 120)
562-8-2
(99171, 121)
562-8-3
(99171, 122)
562-8-4
(99171, 123)
562-8-5
(99171, 124)
562-8-6
(99171, 125)
562-9-1
(99171, 126)
562-9-2
(99171, 127)
562-9-3
(99171, 128)
562-9-4
(99171, 129)
562-9-5
(99171, 130)
562-9-6
(99171, 131)
562-10-1
(99171, 132)
562-10-2
(99171, 133)
562-10-3
(99171, 134)
562-10-4
(99171, 135)
562-10-5
(99171, 136)
562-10-6
(99171, 137)
562-11-1
(99171, 138)
562-11-2
(99171, 139)
562-11-3
(99171, 140)
562-11-4
(99171, 141)
562-11-5
(99171, 142)
562-11-6
(99171, 143)
562-12-1
(99171, 144)
562-12-2
(99171, 145)
562-12-3
(99171, 146)
562-12-4
(99171, 147)
562-12-5
(99171, 148)
562-12-6
(99171, 149)
562-13-1
(99171, 150)
562-13-2
(99171, 151)
562-13-3
(99171, 152)
562-13-4
(99171, 153)
562-13-5
(99171, 154)
562-13-6
(99171, 155)
562-14-1
(99171, 156)
562-14-2
(99171, 157)
562-14-3
(99171, 158)
562-14-4
(99171, 159)
562-14-5
(99171, 160)
562-14-6
(99171, 161)
562-15-1
(99171, 162)
562-15-2
(99171, 163)
562-15-3
(99171, 164)
562-15-4
(99171, 165)
562-15-5
(99171, 166)
562-15-6
(99171, 167)
562-16-1
(99171, 168)
562-16-2
(99171, 169)
562-16-3
(99171, 170)
562-16-4
(99171, 171)
562-16-5
(99171, 172)
562-16-6
(99171, 173)
562-17-1
(99171, 174)
562-17-2
(99171, 175)
562-17-3
(99171, 176)
562-17-4
(99171, 177)
562-17-5
(99171, 178)
562-17-6
(99171, 179)
562-18-1
(99171, 180)
562-18-2
(99171, 181)
562-18-3
(99171, 182)
562-18-4
(99171, 183)
562-18-5
(99171, 184)
562-18-6
(99171, 185)
562-19-1
(99171, 186)
562-19-2
(99171, 187)
562-19-3
(99171, 188)
562-19-4
(99171, 189)
562-19-5
(99171, 190)
562-19-6
(99171, 191)
562-20-1
(99171, 192)
562-20-2
(99171, 193)
562-20-3
(99171, 194)
562-20-4
(99171, 195)
562-20-5
(99171, 196)
562-20-6
(99171, 197)
562-21-1
(99171, 198)
562-21-2
(99171, 199)
562-21-3
(99171, 200)
562-21-4
(99171, 201)
562-21-5
(99171, 202)
562-21-6
(99171, 203)
562-22-1
(99171, 204)
562-22-2
(99171, 205)
562-22-3
(99171, 206)
562-22-4
(99171, 207)
562-22-5
(99171, 208)
562-22-6
(99171, 209)
562-23-1
(99171, 210)
562-23-2
(99171, 211)
562-23-3
(99171, 212)
562-23-4
(99171, 213)
562-24-1
(99171, 214)
562-24-2
(99171, 215)
563-1-1
(99171, 216)
563-1-2
(99171, 217)
563-1-3
(99171, 218)
563-1-4
(99171, 219)
563-1-5
(99171, 220)
563-1-6
(99171, 221)
563-2-1
(99171, 222)
563-2-2
(99171, 223)
563-2-3
(99171, 224)
563-2-4
(99171, 225)
563-2-5
(99171, 226)
563-2-6
(99171, 227)
563-3-1
(99171, 228)
563-3-2
(99171, 229)
563-3-3
(99171, 230)
563-3-4
(99171, 231)
563-3-5
(99171, 232)
563-3-6
(99171, 233)
563-4-1
(99171, 234)
563-4-2
(99171, 235)
563-4-3
(99171, 236)
563-4-4
(99171, 237)
563-4-5
(99171, 238)
563-4-6
(99171, 239)
563-5-1
(99171, 240)
563-5-2
(99171, 241)
563-5-3
(99171, 242)
563-5-4
(99171, 243)
563-5-5
(99171, 244)
563-5-6
(99171, 245)
563-6-1
(99171, 246)
563-6-2
(99171, 247)
563-6-3
(99171, 248)
563-6-4
(99171, 249)
563-6-5
(99171, 250)
563-6-6
(99171, 251)
563-7-1
(99171, 252)
563-7-2
(99171, 253)
563-7-3
(99171, 254)
563-7-4
(99171, 255)
563-7-5
(99171, 256)
563-7-6
(99171, 257)
563-8-1
(99171, 258)
563-8-2
(99171, 259)
563-8-3
(99171, 260)
563-8-4
(99171, 261)
563-8-5
(99171, 262)
563-8-6
(99171, 263)
563-9-1
(99171, 264)
563-9-2
(99171, 265)
563-9-3
(99171, 266)
563-9-4
(99171, 267)
563-9-5
(99171, 268)
563-9-6
(99171, 269)
563-10-1
(99171, 270)
563-10-2
(99171, 271)
563-10-3
(99171, 272)
563-10-4
(99171, 273)
563-10-5
(99171, 274)
563-10-6
(99171, 275)
563-11-1
(99171, 276)
563-11-2
(99171, 277)
563-11-3
(99171, 278)
563-11-4
(99171, 279)
563-11-5
(99171, 280)
563-11-6
(99171, 281)
563-12-1
(99171, 282)
563-12-2
(99171, 283)
563-12-3
(99171, 284)
563-12-4
(99171, 285)
563-12-5
(99171, 286)
563-12-6
(99171, 287)
563-13-1
(99171, 288)
563-13-2
(99171, 289)
563-13-3
(99171, 290)
563-13-4
(99171, 291)
563-13-5
(99171, 292)
563-13-6
(99171, 293)
563-14-1
(99171, 294)
563-14-2
(99171, 295)
563-14-3
(99171, 296)
563-14-4
(99171, 297)
563-14-5
(99171, 298)
563-14-6
(99171, 299)
563-15-1
(99171, 300)
563-15-2
(99171, 301)
563-15-3
(99171, 302)
563-15-4
(99171, 303)
563-15-5
(99171, 304)
563-15-6
(99171, 305)
563-16-1
(99171, 306)
563-16-2
(99171, 307)
563-16-3
(99171, 308)
563-16-4
(99171, 309)
563-16-5
(99171, 310)
563-16-6
(99171, 311)
563-17-1
(99171, 312)
563-17-2
(99171, 313)
563-17-3
(99171, 314)
563-17-4
(99171, 315)
563-17-5
(99171, 316)
563-17-6
(99171, 317)
563-18-1
(99171, 318)
563-18-2
(99171, 319)
563-18-3
(99171, 320)
563-18-4
(99171, 321)
563-18-5
(99171, 322)
563-18-6
(99171, 323)
563-19-1
(99171, 324)
563-19-2
(99171, 325)
563-19-3
(99171, 326)
563-19-4
(99171, 327)
563-19-5
(99171, 328)
563-19-6
(99171, 329)
563-20-1
(99171, 330)
563-20-2
(99171, 331)
563-20-3
(99171, 332)
563-20-4
(99171, 333)
563-20-5
(99171, 334)
563-20-6
(99171, 335)
563-21-1
(99171, 336)
563-21-2
(99171, 337)
563-21-3
(99171, 338)
563-21-4
(99171, 339)
563-21-5
(99171, 340)
563-21-6
(99171, 341)
563-22-1
(99171, 342)
563-22-2
(99171, 343)
563-22-3
(99171, 344)
563-22-4
(99171, 345)
563-22-5
(99171, 346)
563-22-6
(99171, 347)
563-23-1
(99171, 348)
563-23-2
(99171, 349)
563-23-3
(99171, 350)
563-23-4
(99171, 351)
563-24-1
(99171, 352)
563-24-2
(99171, 353)

,YEAR,MONTH,DAY,HOUR,MINUTE,WATER_ACCU_FLOW_561-1-1,WATER_ACCU_FLOW_561-1-2,WATER_ACCU_FLOW_561-1-3,WATER_ACCU_FLOW_561-1-4,WATER_ACCU_FLOW_561-2-1,...,WATER_ACCU_FLOW_563-22-3,WATER_ACCU_FLOW_563-22-4,WATER_ACCU_FLOW_563-22-5,WATER_ACCU_FLOW_563-22-6,WATER_ACCU_FLOW_563-23-1,WATER_ACCU_FLOW_563-23-2,WATER_ACCU_FLOW_563-23-3,WATER_ACCU_FLOW_563-23-4,WATER_ACCU_FLOW_563-24-1,WATER_ACCU_FLOW_563-24-2
0,2022,7,17,23,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022,7,17,23,10,NaN,NaN,25.5143000000,NaN,13.7343000000,...,45.0745000000,41.5518000000,NaN,NaN,NaN,27.6403000000,NaN,47.2909000000,37.9976000000,27.5292000000
2,2022,7,17,23,20,51.8681000000,32.0475000000,25.5143000000,29.7432000000,13.7343000000,...,45.0924000000,41.5794000000,41.3227000000,20.8500000000,21.3106000000,27.6493000000,22.2777000000,47.2911000000,37.9979000000,27.5292000000
3,2022,7,17,23,30,51.8681000000,32.0475000000,25.5143000000,29.7479000000,13.7343000000,...,45.1227000000,41.5794000000,41.3227000000,20.8500000000,21.3107000000,27.6669000000,22.2777000000,47.2911000000,37.9980000000,27.5292000000
4,2022,7,17,23,40,51.8681000000,32.0475000000,25.5143000000,29.7522000000,13.7343000000,...,NaN,41.5896000000,41.3228000000,20.8501000000,21.3109000000,27.6669000000,22.2978000000,47.2912000000,37.9981000000,27.5293000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99166,2024,6,5,14,40,584.5431000000,377.0306000000,366.0932000000,356.9398000000,343.5800000000,...,515.9979000000,423.5142000000,513.6214000000,227.6019000000,334.8898000000,292.1471000000,481.6986000000,471.2254000000,505.5825000000,332.6308000000
99167,2024,6,5,14,50,584.5433000000,377.0306000000,366.0972000000,356.9498000000,343.5800000000,...,515.9979000000,NaN,513.6214000000,227.6019000000,NaN,NaN,NaN,471.2692000000,NaN,NaN
99168,2024,6,5,15,0,584.5434000000,377.0306000000,366.1061000000,356.9526000000,343.5802000000,...,515.9980000000,NaN,513.6215000000,227.6019000000,NaN,NaN,NaN,471.2881000000,NaN,NaN
99169,2024,6,5,15,10,584.5434000000,377.0306000000,366.1282000000,356.9526000000,343.5802000000,...,515.9980000000,NaN,513.6218000000,227.6019000000,NaN,NaN,NaN,471.2881000000,NaN,NaN
99170,2024,6,5,15,20,584.5434000000,377.0306000000,366.1567000000,356.9676000000,343.5802000000,...,NaN,NaN,513.6321000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
list_col = df_kier_h_Combined.columns[6:]
# df_dt_period = df_kier_h_Combined[['METER_DATE']]

df_kier_Calc = df_kier_h_Combined[list_col]
df_kier_extract = df_kier_h_Combined

df_kier_extract['MEAN_OF_ACCU'], df_kier_extract['SUM_OF_ACCU'] = df_kier_Calc.mean(axis = 1), df_kier_Calc.sum(axis = 1)

str_file = 'KIER_' + str_domain + '_ACCU_10MIN.csv'
df_kier_extract.to_csv(str_dirName_h + str_file)